import counterReducer from "./counter";  // importing counter.js from reducer...
import loggedReducer from "./isLogged";  // importing logged.js from reducer...
import { combineReducers } from "redux"; // used to combine the reducers...


// Combining counter and logged reducers in this index.js...
const allReducer = combineReducers({
    counter: counterReducer,
    isLogged: loggedReducer,
});

export default allReducer; // exports all the combined reducers...